### ISSUE TITLE
Invalid path source

### ISSUE THREAD

**Issue by abufikrims** [JDavidMoreno/month_year_widget#1]
Hi ..
Please check assets.xml line 6 and line 12 .. there are invalid source 
<script type="text/javascript" src="/all_month_year_widget/static/lib/tempusdominus.js" />

it must be 
src="/month_year_widget/static/lib/tempusdominus.js" />

**Comment by JDavidMoreno** [comment]
Hey @abufikrims, thanks for the feedback! You're right, that shouldn't be there, I'll fix it now. :)
